### ISSUE TITLE
[M95][Low Power] Use M95 in Low Power configuration 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/talking-fiber#9]
In order to decrease the consumption of Quectel M95 is necessary to use it in Low Power mode and disable it when is not needed. Overview of TODOs:

- Disable M95 when is not needed
- Modify the M95 in order to work in Low Power mode:
`Disable Protections: AT+QVBATT
TX with low power: AT+CDETXPW
` 

Follow recommendations provide by attached guide with special focus to 2.2, 3 and 4. The design of the device is for the battery **ER34615M**

[Quectel_Low_Power_Design_User_Guide_V1.3.pdf](https://github.com/Sinapse-Energia/talking-fiber/files/2344971/Quectel_Low_Power_Design_User_Guide_V1.3.pdf)

**Comment by ralcaide** [comment]
@fpgamcu , any feedback about this task?

**Comment by vAnArhist** [comment]
Now code in AP_based have all listed features (disable M95 and low power mode fixes).
By the way, M95 power enable/disable circuits (Q_10_2, Q_6_2,...) can be removed, because modem have power enable/disable circuits inside it.

**Comment by ralcaide** [comment]
Thank you very much.
We have already performed preliminary testing and seem is working good :). But we found a possible bug:

- The measurement is always the same and the **timestamp** also. It is like the photo-diode is measuring only one time.

The current configuration is: PERIODIC = 60m y ALERTS = 5m.

Any idea?

**Comment by ralcaide** [comment]
Related with the consumption, the HW designer tells that the best option is to disable the all the peripherals after the set power_key to 0. This is possible to be done setting the transistors to 0. 
Could you please do that and test that the re-connections are still working? We think the high consumption in sleep mode is related with that.

**Comment by vAnArhist** [comment]
I have tested with setting EX_ENABLE_GPRS_BATTERY to 0 when not publishing and setting EX_RESET_PHOTODIODE to 0 when not measuring, But it still sometimes going to state when all the time consuming 0.05 A

**Comment by ralcaide** [comment]
This is a bad new, seems that there is some kind of HW problem. 
Could you please push the code that disconnects the peripherals when are not in use? We will try testing in our side and disconnect physically some peripherals in order to understand what is happening

**Comment by vAnArhist** [comment]
The code setting EX_RESET_PHOTODIODE to 0 when not measuring it already there.
The code setting EX_ENABLE_GPRS_BATTERY to 0 sometimes causing power reset of the board (was causing it always before fix with power off the M95 using PWRKEY).
Setting EX_ENABLE_GPRS_BATTERY to 0 while not publishing - uncomment lines 178 179 and 227 in main.c

**Comment by ralcaide** [comment]
Ok thanks, we will test.

**Comment by ralcaide** [comment]
Tested OK.
